### ISSUE TITLE
Homebrew support

### ISSUE THREAD

**Issue by nitrocode** [flosell/trailscraper#105]
Would be nice to install using

```
brew install trailscraper
```

**Comment by kmcquade** [comment]
For anyone who wants this, feel free to use this PR I made to parliament as a reference. https://github.com/duo-labs/parliament/pull/111

**Comment by flosell** [comment]
Hi @nitrocode, similar to our conversation on my other project, agreed, this would be very helpful and I'm happy to support this however I can. 
However, I'd appreciate some help with the initial submission due to homebrews [policy against self-submitting](https://docs.brew.sh/Acceptable-Formulae#niche-or-self-submitted-stuff).

**Comment by nitrocode** [comment]
https://github.com/Homebrew/homebrew-core/pull/54818

**Comment by flosell** [comment]
Homebrew PR is merged, `brew install trailscraper` works now! Thank you @nitrocode for contributing this!
